/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 健康检查（Docker HEALTHCHECK 用）
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cad/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Cad
         * @description 解析 DWG/DXF（Phase 0 占位，完整实现待 A.2 第 2 批）
         */
        post: operations["parse_cad_api_cad_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cad/viewport": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Viewport
         * @description B4 空间查询：bbox 范围内 entity 列表
         */
        post: operations["viewport_api_cad_viewport_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cad/sheets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sheets
         * @description Phase 3：项目下图纸列表（图纸选择器）
         */
        get: operations["get_sheets_api_cad_sheets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cad/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Metadata
         * @description v1.0 §13 GET /api/cad/metadata：图纸元数据 + drawing_type/units/level/zone/revision
         */
        get: operations["get_metadata_api_cad_metadata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cad/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Layers
         * @description v1.0 §13 GET /api/cad/layers：图层列表 + entity_count
         */
        get: operations["get_layers_api_cad_layers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cad/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Blocks
         * @description v1.0 §13 GET /api/cad/blocks：块列表（INSERT block_name）+ insert_count
         */
        get: operations["get_blocks_api_cad_blocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cad/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Entities
         * @description v1.0 §13 GET /api/cad/entities：分页列 entity（layer/block/dxf_type 过滤）
         */
        get: operations["get_entities_api_cad_entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/binding/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Candidates
         * @description Phase 4：候选列表（join BOQ/工程对象展示字段，status 过滤）
         */
        get: operations["candidates_api_binding_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/binding/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate
         * @description 生成绑定候选（4 层：历史→规则→语义→LLM 精排）
         */
        post: operations["generate_api_binding_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/binding/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm
         * @description 确认候选 → 写 mapping + 跨图 SUPERSEDED（reviewer.confirm_binding）
         */
        post: operations["confirm_api_binding_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/binding/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject
         * @description 拒绝候选
         */
        post: operations["reject_api_binding_reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boq/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Boq
         * @description 解析 BOQ Excel（B1 修复：4 种表头识别，A.2 第 2 批 P0-6 落实）
         */
        post: operations["parse_boq_api_boq_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boq/writeback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Writeback
         * @description 回写 measured_qty（B5 S7 Excel 保真回写，P0-15 落实）
         */
        post: operations["writeback_api_boq_writeback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boq/writeback-to-excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Writeback To Excel
         * @description P4 v1.0 §6.4 W1-W6 Excel 保真回写：
         *     W1 保公式加载 → W2 只写新增列 → W3 新表头样式 → W4 完整性校验 → W5 锁文件回退 → W6 审计
         */
        post: operations["writeback_to_excel_api_boq_writeback_to_excel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boq/writeback-audited": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Writeback Audited
         * @description v1.0 §6.4 完整 Excel 保真回写契约：
         *     1. 算 source_file_path 的 SHA-256
         *     2. 写回 measured_qty（不动 original_qty / bill_qty / formula / merge_cells）
         *     3. writeback_audit.file_sha256 记录 SHA-256
         *     4. 返回 SHA-256 + audited_rows（人工可对比校验）
         */
        post: operations["writeback_audited_api_boq_writeback_audited_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boq/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Boq
         * @description v1.0 §15 工程量回写：导出实测值到 Excel（overwrite_original=False 保留对照列）
         */
        post: operations["export_boq_api_boq_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dataset Placeholder
         * @description P0-22 测试数据通路占位（Phase 1 实现）
         */
        get: operations["dataset_placeholder_api_dataset_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/mark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark
         * @description 手动标记一条测试数据（#3 决策）
         */
        post: operations["mark_api_dataset_mark_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deactivate
         * @description 停用一条测试数据
         */
        post: operations["deactivate_api_dataset_deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/manifests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Manifests
         * @description v1.0 §8 列出所有 dataset 目录
         */
        get: operations["list_manifests_api_dataset_manifests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Manifest
         * @description v1.0 §8 读指定 dataset 的 manifest.json
         */
        get: operations["get_manifest_api_dataset_manifest_get"];
        put?: never;
        /**
         * Update Manifest
         * @description v1.0 §8 更新 manifest 单字段
         */
        post: operations["update_manifest_api_dataset_manifest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description 列出 Jobs（按状态过滤）
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description 按状态统计 job 数（Round 7 增强：监控/管理面板）
         */
        get: operations["get_stats_api_jobs_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tasks
         * @description 列出可提交的任务名（func_name 注册表）
         */
        get: operations["list_tasks_api_jobs_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cleanup Jobs
         * @description 清理旧 completed/failed/cancelled jobs（避免内存无限增长）
         *
         *     keep_completed: 保留最近 N 个 completed（默认 50）
         */
        post: operations["cleanup_jobs_api_jobs_cleanup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Job
         * @description 提交一个 Job（Phase 2：按注册表 func_name 提交真实业务任务）
         *
         *     func_name 取值（webapi/jobs/tasks.py TASKS）：
         *       - boq.parse        解析 BOQ Excel
         *       - cad.parse         解析 CAD/DWG 文件
         *       - extraction.run   工程对象提取（设备/线性/面积）
         *       - takeoff.sheet     单图 takeoff（6 阶段管线）
         *       - takeoff.folder    文件夹 takeoff（多图聚合）
         *       - binding.generate  生成绑定候选（4 层）
         */
        post: operations["submit_job_api_jobs_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Job
         * @description SSE 端点：实时推送 job 进度 + 终态
         */
        get: operations["stream_job_api_jobs__job_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extraction/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Extraction
         * @description 触发工程对象提取（设备/线性/面积 三类）
         */
        post: operations["run_extraction_api_extraction_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extraction/eos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Eos
         * @description 列出工程对象（可按 sheet_id / object_type 过滤）
         */
        get: operations["list_eos_api_extraction_eos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/takeoff/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Takeoff
         * @description 触发 AI 算量（单图或文件夹维度）
         */
        post: operations["run_takeoff_api_takeoff_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description 读 llm_settings 单例表（#9 后端转发 5 后端配置）
         */
        get: operations["get_settings_api_llm_settings_get"];
        /**
         * Update Settings
         * @description 部分字段更新 llm_settings
         */
        put: operations["update_settings_api_llm_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description 通用 chat 端点（#9 后端转发）
         */
        post: operations["chat_api_llm_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/llm-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Llm Runs
         * @description 读 llm_run 审计表（按 project_id + task_type 过滤）
         */
        get: operations["list_llm_runs_api_audit_llm_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Overview
         * @description 项目总览（boq_count / eo_breakdown / writeback_by_takability / llm_runs_by_task）
         */
        get: operations["get_overview_api_audit_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/precheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Precheck
         * @description v1.0 §29 预检页面 6 维度（drawing_type / takability / coverage / granularity / version / provisional）
         */
        get: operations["get_precheck_api_audit_precheck_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cad-standard/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Rules
         * @description v1.0 §26 列出 5 个规则文件（layer_rules / block_rules / attribute_rules / drawing_type_rules / specification_rules）
         */
        get: operations["list_rules_api_cad_standard_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cad-standard/rules/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rule
         * @description v1.0 §26 读单个规则 JSON
         */
        get: operations["get_rule_api_cad_standard_rules__name__get"];
        /**
         * Update Rule
         * @description v1.0 §26 更新规则 JSON（按 schema 校验）
         */
        put: operations["update_rule_api_cad_standard_rules__name__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChatRequest */
        ChatRequest: {
            /**
             * System
             * @default
             */
            system: string;
            /** User */
            user: string;
            /**
             * Images
             * @description base64 编码图片列表（Phase 2 占位）
             */
            images?: string[];
            /**
             * Task Type
             * @default chat
             */
            task_type: string;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Task Type */
            task_type: string;
            /** Model */
            model: string;
            /** Output */
            output: unknown;
        };
        /** ConfirmBindingRequest */
        ConfirmBindingRequest: {
            /** Candidate Id */
            candidate_id: number;
            /**
             * By User
             * @default sysadmin
             */
            by_user: string;
        };
        /** DeactivateRequest */
        DeactivateRequest: {
            /** Entry Id */
            entry_id: number;
        };
        /** EngineeringObjectRead */
        EngineeringObjectRead: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Sheet Id */
            sheet_id?: number | null;
            /**
             * Object Type
             * @default
             */
            object_type: string;
            /**
             * Discipline
             * @default
             */
            discipline: string;
            /**
             * System
             * @default
             */
            system: string;
            /**
             * Block Name
             * @default
             */
            block_name: string;
            /**
             * Layer Name
             * @default
             */
            layer_name: string;
            /**
             * Specification
             * @default
             */
            specification: string;
            /**
             * Unit
             * @default
             */
            unit: string;
            /**
             * Quantity Rule
             * @default count
             */
            quantity_rule: string;
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /**
             * Source
             * @default
             */
            source: string;
        };
        /**
         * ExportBoqRequest
         * @description v1.0 §15 工程量回写：导出实测值到 Excel
         */
        ExportBoqRequest: {
            /** Project Id */
            project_id: number;
            /**
             * Output Path
             * @description 输出 xlsx 绝对路径
             */
            output_path: string;
            /**
             * Overwrite Original
             * @description 是否覆盖原 BOQ 数量列（默认保留对照）
             * @default false
             */
            overwrite_original: boolean;
        };
        /** ExportBoqResponse */
        ExportBoqResponse: {
            /** Project Id */
            project_id: number;
            /** Output Path */
            output_path: string;
            /** Written Rows */
            written_rows: number;
            /**
             * Skipped Rows
             * @default 0
             */
            skipped_rows: number;
            /** By Takability */
            by_takability?: Record<string, never>;
        };
        /** ExtractionRequest */
        ExtractionRequest: {
            /** Project Id */
            project_id: number;
            /** Sheet Id */
            sheet_id: number;
            /** Layer Rules */
            layer_rules?: Record<string, never>;
        };
        /** ExtractionResponse */
        ExtractionResponse: {
            /** Project Id */
            project_id: number;
            /** Sheet Id */
            sheet_id: number;
            /** Created */
            created: number;
            /** Stats */
            stats?: Record<string, never>;
            /** Object Ids */
            object_ids?: number[];
        };
        /** GenerateCandidatesRequest */
        GenerateCandidatesRequest: {
            /** Project Id */
            project_id: number;
            /** Sheet Id */
            sheet_id?: number | null;
            /**
             * Use Llm
             * @default true
             */
            use_llm: boolean;
            /**
             * Top N
             * @default 5
             */
            top_n: number;
        };
        /** GenerateCandidatesResponse */
        GenerateCandidatesResponse: {
            /** Project Id */
            project_id: number;
            /** Sheet Id */
            sheet_id?: number | null;
            /** Use Llm */
            use_llm: boolean;
            /** Candidates Created */
            candidates_created: number;
            /** Stats */
            stats?: Record<string, never>;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobSubmitRequest */
        JobSubmitRequest: {
            /** Name */
            name: string;
            /**
             * Func Name
             * @default
             */
            func_name: string;
            /**
             * Payload
             * @default {}
             */
            payload: Record<string, never>;
        };
        /**
         * LlmSettingsRead
         * @description llm_settings 单例表读取（PG/PG-asyncio 同步）
         */
        LlmSettingsRead: {
            /**
             * Id
             * @default 1
             */
            id: number;
            /**
             * Active Backend
             * @default ollama
             */
            active_backend: string;
            /**
             * Ollama Host
             * @default http://127.0.0.1:11434
             */
            ollama_host: string;
            /**
             * Ollama Model
             * @default qwen2.5:7b
             */
            ollama_model: string;
            /**
             * Dashscope Api Key
             * @default
             */
            dashscope_api_key: string;
            /**
             * Dashscope Model
             * @default qwen-vl-max-0809
             */
            dashscope_model: string;
            /**
             * Openai Api Key
             * @default
             */
            openai_api_key: string;
            /**
             * Openai Model
             * @default gpt-4o-mini
             */
            openai_model: string;
            /**
             * Deepseek Api Key
             * @default
             */
            deepseek_api_key: string;
            /**
             * Deepseek Model
             * @default deepseek-chat
             */
            deepseek_model: string;
            /**
             * Custom Base Url
             * @default
             */
            custom_base_url: string;
            /**
             * Custom Api Key
             * @default
             */
            custom_api_key: string;
            /**
             * Custom Model
             * @default
             */
            custom_model: string;
            /**
             * Custom Embedding Model
             * @default
             */
            custom_embedding_model: string;
            /**
             * Fallback Enabled
             * @default 0
             */
            fallback_enabled: number;
            /**
             * Fallback Backend
             * @default
             */
            fallback_backend: string;
            /**
             * Quality Threshold
             * @default 0.7
             */
            quality_threshold: number;
            /**
             * Temperature
             * @default 0.1
             */
            temperature: number;
            /**
             * Timeout
             * @default 120
             */
            timeout: number;
            /**
             * Max Tokens
             * @default 4000
             */
            max_tokens: number;
            /**
             * Updated At
             * @default
             */
            updated_at: string;
        };
        /**
         * LlmSettingsUpdate
         * @description 部分字段更新
         */
        LlmSettingsUpdate: {
            /** Active Backend */
            active_backend?: string | null;
            /** Ollama Host */
            ollama_host?: string | null;
            /** Ollama Model */
            ollama_model?: string | null;
            /** Dashscope Api Key */
            dashscope_api_key?: string | null;
            /** Dashscope Model */
            dashscope_model?: string | null;
            /** Openai Api Key */
            openai_api_key?: string | null;
            /** Openai Model */
            openai_model?: string | null;
            /** Deepseek Api Key */
            deepseek_api_key?: string | null;
            /** Deepseek Model */
            deepseek_model?: string | null;
            /** Custom Base Url */
            custom_base_url?: string | null;
            /** Custom Api Key */
            custom_api_key?: string | null;
            /** Custom Model */
            custom_model?: string | null;
            /** Custom Embedding Model */
            custom_embedding_model?: string | null;
            /** Fallback Enabled */
            fallback_enabled?: number | null;
            /** Fallback Backend */
            fallback_backend?: string | null;
            /** Quality Threshold */
            quality_threshold?: number | null;
            /** Temperature */
            temperature?: number | null;
            /** Timeout */
            timeout?: number | null;
            /** Max Tokens */
            max_tokens?: number | null;
        };
        /** ManifestUpdateRequest */
        ManifestUpdateRequest: {
            /**
             * Dataset Id
             * @default lbh
             */
            dataset_id: string;
            /** Key */
            key: string;
            /** Value */
            value: string;
        };
        /** MarkRequest */
        MarkRequest: {
            /** Name */
            name: string;
            /** Project Id */
            project_id: number;
            /** File Path */
            file_path: string;
            /** Data Type */
            data_type: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** OverviewResponse */
        OverviewResponse: {
            /** Project Id */
            project_id: number;
            /** Boq Count */
            boq_count: number;
            /** Mapping Count */
            mapping_count: number;
            /** Eo Breakdown */
            eo_breakdown: Record<string, never>[];
            /** Writeback By Takability */
            writeback_by_takability: Record<string, never>[];
            /** Llm Runs By Task */
            llm_runs_by_task: Record<string, never>[];
        };
        /** ParseBoqRequest */
        ParseBoqRequest: {
            /** Project Id */
            project_id: number;
            /**
             * File Path
             * @description xlsx/xls 绝对路径
             */
            file_path: string;
        };
        /** ParseBoqResponse */
        ParseBoqResponse: {
            /** Project Id */
            project_id: number;
            /** File Path */
            file_path: string;
            /** Item Count */
            item_count: number;
            /** Meta */
            meta?: Record<string, never>;
        };
        /** ParseRequest */
        ParseRequest: {
            /** Project Id */
            project_id: number;
            /**
             * File Path
             * @description DWG/DXF 绝对路径（先上传到 DRAWING_CACHE_DIR）
             */
            file_path: string;
        };
        /** ParseResponse */
        ParseResponse: {
            /** Project Id */
            project_id: number;
            /** File Path */
            file_path: string;
            /** Entity Count */
            entity_count: number;
            /** Layer Count */
            layer_count: number;
        };
        /** RejectBindingRequest */
        RejectBindingRequest: {
            /** Candidate Id */
            candidate_id: number;
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * By User
             * @default sysadmin
             */
            by_user: string;
        };
        /** RuleUpdateRequest */
        RuleUpdateRequest: {
            /** Content */
            content: Record<string, never>;
        };
        /** TakeoffRequest */
        TakeoffRequest: {
            /** Project Id */
            project_id: number;
            /** Sheet Id */
            sheet_id?: number | null;
            /**
             * Folder Path
             * @default
             */
            folder_path: string;
        };
        /** TakeoffResponse */
        TakeoffResponse: {
            /** Project Id */
            project_id: number;
            /** Sheet Id */
            sheet_id?: number | null;
            /**
             * Folder Path
             * @default
             */
            folder_path: string;
            /** Result */
            result?: Record<string, never>;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ViewportQuery
         * @description B4 空间查询请求
         */
        ViewportQuery: {
            /** Sheet Id */
            sheet_id: number;
            /** Min X */
            min_x: number;
            /** Min Y */
            min_y: number;
            /** Max X */
            max_x: number;
            /** Max Y */
            max_y: number;
            /**
             * Limit
             * @default 10000
             */
            limit: number;
        };
        /**
         * WritebackAuditedRequest
         * @description 回写 + 源文件 SHA-256 审计（v1.0 §6.4 防 tamper）
         */
        WritebackAuditedRequest: {
            /** Project Id */
            project_id: number;
            /**
             * Project Scale
             * @default 1
             */
            project_scale: number;
            /**
             * Source File Path
             * @default
             */
            source_file_path: string;
        };
        /** WritebackAuditedResponse */
        WritebackAuditedResponse: {
            /** Project Id */
            project_id: number;
            /** Written */
            written: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * File Sha256
             * @default
             */
            file_sha256: string;
            /**
             * Audited Rows
             * @default 0
             */
            audited_rows: number;
        };
        /** WritebackRequest */
        WritebackRequest: {
            /** Project Id */
            project_id: number;
            /**
             * Project Scale
             * @default 1
             */
            project_scale: number;
        };
        /** WritebackResponse */
        WritebackResponse: {
            /** Project Id */
            project_id: number;
            /** Written */
            written: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
        };
        /**
         * WritebackToExcelRequest
         * @description P4 v1.0 §6.4：Excel 保真回写请求（打开原 Excel，新增列写 measured_qty）
         */
        WritebackToExcelRequest: {
            /** Project Id */
            project_id: number;
            /**
             * Source File Path
             * @description BOQ 源 Excel 绝对路径（xlsx/xls）
             */
            source_file_path: string;
            /**
             * Project Scale
             * @default 1
             */
            project_scale: number;
        };
        /**
         * WritebackToExcelResponse
         * @description P4 v1.0 §6.4：Excel 保真回写响应
         */
        WritebackToExcelResponse: {
            /** Project Id */
            project_id: number;
            /** Source File Path */
            source_file_path: string;
            /** Output Path */
            output_path: string;
            /** Written */
            written: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Total Items
             * @default 0
             */
            total_items: number;
            /**
             * Verified
             * @default false
             */
            verified: boolean;
            /**
             * Target Col
             * @default 0
             */
            target_col: number;
            /**
             * File Sha256
             * @default
             */
            file_sha256: string;
            /** Integrity */
            integrity?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    parse_cad_api_cad_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    viewport_api_cad_viewport_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewportQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sheets_api_cad_sheets_get: {
        parameters: {
            query: {
                project_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metadata_api_cad_metadata_get: {
        parameters: {
            query: {
                sheet_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_layers_api_cad_layers_get: {
        parameters: {
            query: {
                sheet_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_blocks_api_cad_blocks_get: {
        parameters: {
            query: {
                sheet_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entities_api_cad_entities_get: {
        parameters: {
            query: {
                sheet_id: number;
                layer?: string | null;
                block_name?: string | null;
                dxf_type?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    candidates_api_binding_candidates_get: {
        parameters: {
            query: {
                project_id: number;
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_api_binding_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateCandidatesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateCandidatesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_api_binding_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmBindingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_api_binding_reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectBindingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_boq_api_boq_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseBoqRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseBoqResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    writeback_api_boq_writeback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritebackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WritebackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    writeback_to_excel_api_boq_writeback_to_excel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritebackToExcelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WritebackToExcelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    writeback_audited_api_boq_writeback_audited_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritebackAuditedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WritebackAuditedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_boq_api_boq_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportBoqRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportBoqResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_placeholder_api_dataset_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    mark_api_dataset_mark_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_api_dataset_deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeactivateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_manifests_api_dataset_manifests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_manifest_api_dataset_manifest_get: {
        parameters: {
            query?: {
                dataset_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_manifest_api_dataset_manifest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManifestUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_jobs_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    list_tasks_api_jobs_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    cleanup_jobs_api_jobs_cleanup_post: {
        parameters: {
            query?: {
                keep_completed?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_job_api_jobs_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_job_api_jobs__job_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_extraction_api_extraction_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_eos_api_extraction_eos_get: {
        parameters: {
            query: {
                project_id: number;
                sheet_id?: number | null;
                object_type?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineeringObjectRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_takeoff_api_takeoff_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TakeoffRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TakeoffResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_llm_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmSettingsRead"];
                };
            };
        };
    };
    update_settings_api_llm_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LlmSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmSettingsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_llm_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_llm_runs_api_audit_llm_runs_get: {
        parameters: {
            query: {
                project_id: number;
                task_type?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overview_api_audit_overview_get: {
        parameters: {
            query: {
                project_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_precheck_api_audit_precheck_get: {
        parameters: {
            query: {
                project_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_cad_standard_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_rule_api_cad_standard_rules__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rule_api_cad_standard_rules__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
